// <auto-generated />
using System;

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

using People.Identity.Infrastructure.Persistence;

#nullable disable

namespace People.Identity.Infrastructure.Migrations
{
  [DbContext(typeof(IdentityDbContext))]
  [Migration("20231017143740_InitialCreate")]
  partial class InitialCreate
  {
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
      modelBuilder
          .HasAnnotation("ProductVersion", "7.0.12")
          .HasAnnotation("Relational:MaxIdentifierLength", 63);

      NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

      modelBuilder.Entity("People.Identity.Domain.UserAggregate.User", b =>
          {
            b.Property<Guid>("Id")
                      .HasColumnType("uuid");

            b.Property<DateTime>("CreatedDateTime")
                      .HasColumnType("timestamp with time zone");

            b.Property<string>("Email")
                      .IsRequired()
                      .HasColumnType("text");

            b.Property<string>("FirstName")
                      .IsRequired()
                      .HasMaxLength(100)
                      .HasColumnType("character varying(100)");

            b.Property<string>("LastName")
                      .IsRequired()
                      .HasMaxLength(100)
                      .HasColumnType("character varying(100)");

            b.Property<string>("Password")
                      .IsRequired()
                      .HasColumnType("text");

            b.Property<DateTime>("UpdatedDateTime")
                      .HasColumnType("timestamp with time zone");

            b.HasKey("Id");

            b.ToTable("Users", (string)null);
          });
#pragma warning restore 612, 618
    }
  }
}
